### ISSUE TITLE
Error log cant send in discord

### ISSUE THREAD

**Issue by ghost** [twopg/Dashboard#3]
(node:768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:768) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'access_token' of undefined
    at /rbd/pnpm-volume/c9d30868-6572-497f-8930-4a06af53d3ff/node_modules/.registry.npmjs.org/disco-oauth/4.2.7/node_modules/disco-oauth/lib/client.js:165:25
    at new Promise (<anonymous>)
    at Client.getUser (/rbd/pnpm-volume/c9d30868-6572-497f-8930-4a06af53d3ff/node_modules/.registry.npmjs.org/disco-oauth/4.2.7/node_modules/disco-oauth/lib/client.js:158:12)
at /app/src/api/routes/api-routes.ts:32:35
at step (/app/src/api/routes/api-routes.ts:33:23)
at Object.next (/app/src/api/routes/api-routes.ts:14:53)
at /app/src/api/routes/api-routes.ts:8:71
    at new Promise (<anonymous>)
at __awaiter (/app/src/api/routes/api-routes.ts:4:12)
at /app/src/api/routes/api-routes.ts:29:37
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/c9d30868-6572-497f-8930-4a06af53d3ff/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/c9d30868-6572-497f-8930-4a06af53d3ff/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/rbd/pnpm-volume/c9d30868-6572-497f-8930-4a06af53d3ff/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/c9d30868-6572-497f-8930-4a06af53d3ff/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/c9d30868-6572-497f-8930-4a06af53d3ff/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/rbd/pnpm-volume/c9d30868-6572-497f-8930-4a06af53d3ff/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)
(node:768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
[1] Kept https://buzzdash.glitch.me alive.
[2] Kept https://buzzdash.glitch.me alive.
[3] Kept https://buzzdash.glitch.me alive.
[4] Kept https://buzzdash.glitch.me alive.
> 2pg@1.0.0 start:bot /app
> ts-node src/bot.ts
> 2pg@1.0.0 start:bot /app
> ts-node src/bot.ts
[20:37:52] INFO [OTHER] API is live on port 3000
[20:38:20] INFO [EVENTS] Loaded: 8 handlers
[20:38:20] INFO [EVENTS] Loaded: 4 custom handlers
(node:1229) UnhandledPromiseRejectionWarning: AbortError: The user aborted a request.
    at RequestHandler.execute (/rbd/pnpm-volume/c9d30868-6572-497f-8930-4a06af53d3ff/node_modules/.registry.npmjs.org/discord.js/12.3.1/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:1229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1229) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[20:38:22] INFO [BOT] Connected to db
[1] Kept https://buzzdash.glitch.me alive.
[2] Kept https://buzzdash.glitch.me alive.
[3] Kept https://buzzdash.glitch.me alive.
[4] Kept https://buzzdash.glitch.me alive.

**Comment by theADAMJR** [comment]
These are not 2PG bugs.
I made a pull request to disco-oauth to fix the first error - https://github.com/TheDrone7/disco-oauth/pull/27/commits
The second error occurs due to login request or bot token problems.

**Comment by ghost** [comment]
> These are not 2PG bugs.
> I made a pull request to disco-oauth to fix the first error - https://github.com/TheDrone7/disco-oauth/pull/27/commits
> The second error occurs due to login request or bot token problems.

Wdym bot token problems?
